CREATE TABLE plans (id serial PRIMARY KEY, name text NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE users (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, plan_id int NOT NULL REFERENCES plans(id), email text NOT NULL);
