import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { stringify } from "yaml";
import { OpenApiSpec, type OperationSketch } from "./openapi.js";

/** Where the last run's OpenAPI coverage is kept for `slicetest gen --uncovered`. */
export function coverageCacheFile(root: string) {
  return path.join(root, "node_modules", ".cache", "slicetest", "openapi-coverage.json");
}

export interface GenOptions {
  /** The app's spec, relative to `root`. */
  spec: string;
  /** Directory for the scenario files, relative to `root`. Default `scenarios`. */
  out?: string;
  /** Only responses the last run didn't produce. */
  uncovered?: boolean;
  force?: boolean;
}

interface Step {
  [key: string]: unknown;
}

/**
 * Scenario skeletons for the documented responses of an OpenAPI spec, one
 * `<resource>.gen.scenario.yaml` per first path segment. A 2xx response gets a
 * runnable scenario, with a request built from the spec and, when the path
 * needs an id, a step that creates the resource first through the collection's
 * POST. Other responses become skipped scenarios: a to-do list of the states
 * the tests still have to arrange.
 */
export async function gen(root: string, opts: GenOptions) {
  const spec = await OpenApiSpec.load(path.resolve(root, opts.spec), opts.spec);
  const ops = spec.operations();
  let covered = new Set<string>();
  if (opts.uncovered) {
    const cache = coverageCacheFile(root);
    if (!existsSync(cache)) throw new Error("slicetest: no coverage from a previous run yet. Run the scenarios once (with `openapi` set), then `slicetest gen --uncovered`.");
    covered = new Set(JSON.parse(await readFile(cache, "utf8")) as string[]);
  }

  const files = new Map<string, { name: string; skip?: true; steps: Step[] }[]>();
  let count = 0;
  for (const op of ops) {
    for (const key of op.responses) {
      if (covered.has(`${op.method} ${op.template} ${key}`)) continue;
      const resource = op.template.split("/").find((s) => s && !s.startsWith("{")) ?? "root";
      const list = files.get(resource) ?? [];
      list.push(scenarioFor(op, key, ops));
      files.set(resource, list);
      count++;
    }
  }

  const dir = path.resolve(root, opts.out ?? "scenarios");
  const written: string[] = [];
  const skipped: string[] = [];
  for (const [resource, scenarios] of files) {
    const file = path.join(dir, `${resource}.gen.scenario.yaml`);
    const rel = path.relative(root, file);
    if (existsSync(file) && !opts.force) {
      skipped.push(rel);
      continue;
    }
    const header = [
      "# yaml-language-server: $schema=https://unpkg.com/slicetest/schema/scenario.schema.json",
      `# Generated by \`slicetest gen\` from ${opts.spec}${opts.uncovered ? " (responses the last run didn't cover)" : ""}.`,
      "# Requests are built from the spec's examples and schemas: adjust them to your data, then drop the `skip`s one by one.",
      "",
    ].join("\n");
    await mkdir(dir, { recursive: true });
    await writeFile(file, header + stringify({ scenarios }, { lineWidth: 0, aliasDuplicateObjects: false }));
    written.push(rel);
  }
  return { written, skipped, count };
}

function scenarioFor(op: OperationSketch, key: string, all: OperationSketch[]) {
  const steps: Step[] = [];
  let pathText = op.template;
  const success = /^2/.test(key);
  let unresolved = false;
  for (const [name, sample] of Object.entries(op.pathParams)) {
    const creator = success ? creatorFor(op, name, all) : undefined;
    if (creator) {
      steps.push(requestStep(creator.op, creator.op.template, { status: Number(creator.status) }, { [name]: `json.${creator.field}` }));
      pathText = pathText.replace(`{${name}}`, `{{${name}}}`);
    } else {
      pathText = pathText.replace(`{${name}}`, encodeURIComponent(String(sample ?? 1)));
      unresolved = true;
    }
  }
  const status = /^\d{3}$/.test(key) ? Number(key) : undefined;
  // Two error responses need no arranging: a made-up id is not found, and an empty body is invalid.
  const notFound = status === 404 && Object.keys(op.pathParams).length > 0;
  const invalid = (status === 400 || status === 422) && isFilledObject(op.json);
  steps.push(requestStep(invalid ? { ...op, json: {} } : op, pathText, { status }));
  const name = `${op.method} ${op.template} → ${key}${op.summary ? ` (${op.summary})` : ""}`;
  const runnable = success ? !unresolved : notFound || invalid;
  return runnable ? { name, steps } : { name: `${name} — TODO: arrange the state that produces this`, skip: true as const, steps };
}

/**
 * The POST on the collection above `template` whose success response carries
 * the value for `param`: `{id}` in `/polls/{id}/votes` comes from `POST /polls`'s `id`.
 */
function creatorFor(op: OperationSketch, param: string, all: OperationSketch[]) {
  const i = op.template.indexOf(`{${param}}`);
  const collection = op.template.slice(0, i).replace(/\/$/, "");
  const post = all.find((o) => o.method === "POST" && o.template === collection);
  if (!post) return undefined;
  const field = [param, "id"].find((f) => post.createdFields.includes(f));
  const status = post.responses.filter((k) => /^2\d\d$/.test(k)).sort()[0];
  return field && status ? { op: post, field, status } : undefined;
}

function requestStep(op: OperationSketch, pathText: string, expect: { status?: number }, capture?: Record<string, string>): Step {
  const step: Step = { request: `${op.method} ${pathText}` };
  if (Object.keys(op.query).length) step.query = Object.fromEntries(Object.entries(op.query).map(([k, v]) => [k, String(v)]));
  if (op.json !== undefined) step.json = op.json;
  if (expect.status) step.expect = { status: expect.status };
  if (capture) step.capture = capture;
  return step;
}

function isFilledObject(v: unknown) {
  return !!v && typeof v === "object" && !Array.isArray(v) && Object.keys(v).length > 0;
}
